# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de694464580dea8f0d0e587d4d741efa55848d411069f423feb992ca9b274e7ddba978f0ca721af94ef2d7ff771b895a8d8ea916baa1ef71491a262415a1ace5

test:
  secret_key_base: f98a9859b78deb268be7c8f5acb6eea80f284d9c976d7bc728a2bbfaf2b8e43651211f1bee2651d3aaeb06eb5b1135e6ac67ab4f3c71a1ad91610ea80df40c18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
